name: aeolus_py38
channels:
- conda-forge
dependencies:
- python=3.8
- cartopy
- dask
- flake8-builtins!=1.4.0
- flake8-comprehensions
- flake8-copyright
- flake8-docstrings
- flake8-import-order
- flake8-mutable
- flake8-pep3101
- flake8-print
- flake8-quotes
- iris>=2.3
- matplotlib>=3.0
# - metpy>=0.11
- mo_pack
- numpy
- pep8-naming
- pip
- pytest>=2.4
- pytest-cov
- pytest-flake8
# - pyvista>=0.23
# - xarray
- pip:
  - latlon23
