package:
  name: aeolus
  version: {{ environ['VERSION'] }}

source:
  git_url: https://github.com/exoclim/aeolus.git

requirements:
  build:
    - python=3.7
    - setuptools
    - numpy>=1.16
    - iris>=2.3
    - matplotlib>=2
    - pyvista
  run:
    - python=3.7
    - numpy>=1.16
    - iris>=2.3
    - matplotlib>=2
    - pyvista

build:
  script_env:
    - VERSION
    - CONDA_BLD_PATH

test:
  imports:
    - aeolus
    - numpy
    - iris

about:
  home: https://exoclim.github.io/aeolus
  license: LGPL-3.0 
  license_file: LICENSE
  summary: "Python library for object-oriented analysis of atmospheric model output built on top of iris."
  dev_url: https://github.com/exoclim/aeolus
  doc_url: https://exoclim.github.io/aeolus
